### ISSUE TITLE
Some mixes show multiples of flavours, due to 10% limitation of the old mixing system, possibly combine multiples?

### ISSUE THREAD

**Issue by scrib-bler** [snkenjoi/8bvDIY#8]
> [t4r24n] got a question, on some of the recipes it has the same flavor 2 times with the same %, like on just skittles, it has skittles by vapours r us at 10%, 2 times, does that mean its 20% or is it an error and its just 10%?
> [Scribbler] it means 20%
> [t4r24n] ok thank you
> [Scribbler] it's because the old custom mixer only went up to 10% of each flavour
> [Scribbler] so if you wanted more than 10% of a flavour you had to add it twice
> [Scribbler] and the juice database just uses the old custom mix database data

Not sure if this is best dealt with in the database itself by barf (so that they're combined on the database before being sent to the mix calc), or if combining things with the same name would be easier to implement in the mixer itself.

Super simple fix would be a disclaimer type thing explaining why some flavourings are displayed twice.

THE FUTURE IS IN YOUR HANDS! or barfs.

Whatever.

Shut up.

Thanks. <3

**Comment by kirjavascript** [comment]
# dupe flavours are now combined :8ball:
